### PR TITLE
Fixed ISE in NetigenSplashFragment, closes #121

### LINKED ISSUE #121: NetigenSplashFragment$showConsent ISE Piano
java.lang.IllegalStateException: 
at androidx.fragment.app.FragmentManagerImpl.checkStateLoss (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.addAddedFragments (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.addBackStackState (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.addFragment (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.addRetainedFragment (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.animateRemoveFragment (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.attachController (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.beginTransaction (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.completeExecute (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.dispatchConfigurationChanged (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.dispatchContextItemSelected (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.dispatchCreateOptionsMenu (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.dispatchMultiWindowModeChanged (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.dispatchOnFragmentActivityCreated (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.dispatchOnFragmentAttached (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.dispatchOnFragmentViewCreated (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.dispatchOptionsMenuClosed (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.dump (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.enqueueAction (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.executeOps (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.executePostponedTransaction (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.findFragmentById (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.findFragmentByTag (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.getFragment (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.loadAnimation (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.makeFadeAnimation (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.makeOpenCloseAnimation (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.popBackStack (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.popBackStackState (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.postponePostponableTransactions (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.putFragment (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.restoreSaveState (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.setBackStackIndex (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.setMaxLifecycle (FragmentManagerImpl.java)
at androidx.fragment.app.FragmentManagerImpl.throwException (FragmentManagerImpl.java)
at androidx.fragment.app.BackStackRecord.bumpBackStackNesting (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.commit (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.commitInternal (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.doAddOp (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.dump (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.dump (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.expandOps (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.generateOps (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.interactsWith (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.remove (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.setOnStartPostponedListener (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.bumpBackStackNesting (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.commit (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.commitInternal (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.doAddOp (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.dump (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.dump (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.expandOps (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.generateOps (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.interactsWith (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.remove (BackStackRecord.java)
at androidx.fragment.app.BackStackRecord.setOnStartPostponedListener (BackStackRecord.java)
at androidx.fragment.app.DialogFragment.dismissInternal (DialogFragment.java)
at androidx.fragment.app.DialogFragment.onAttach (DialogFragment.java)
at androidx.fragment.app.DialogFragment.setupDialog (DialogFragment.java)
at androidx.fragment.app.DialogFragment.show (DialogFragment.java)
at androidx.fragment.app.DialogFragment.show (DialogFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.initGDPRFragment (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.access$onConsentInfoUpdated (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.access$onCreateWithAds (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.access$setConsentNotShowed$p (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.clickAcceptPolicy (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.onAttach (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.onConsentInfoUpdated (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.setViewModel (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.access$onConsentInfoUpdated (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.access$onCreateWithAds (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.access$setConsentNotShowed$p (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.clickAcceptPolicy (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.onAttach (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.onConsentInfoUpdated (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment.setViewModel (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment$showConsent$2.onConsentInfoUpdated (NetigenSplashFragment.java)
at pl.netigen.core.netigenapi.NetigenSplashFragment$showConsent$2.onFailedToUpdateConsentInfo (NetigenSplashFragment.java)
at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground (ConsentInformation.java)
at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.makeConsentLookupRequest (ConsentInformation.java)
at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.onPostExecute (ConsentInformation.java)
at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.readStream (ConsentInformation.java)
at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.onPostExecute (ConsentInformation.java)
at android.os.AsyncTask.finish (AsyncTask.java:651)
at android.os.AsyncTask.access$500 (AsyncTask.java:180)
at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:668)
at android.os.Handler.dispatchMessage (Handler.java:102)
at android.os.Looper.loop (Looper.java:158)
at android.app.ActivityThread.main (ActivityThread.java:7230)
at java.lang.reflect.Method.invoke (Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

### PR DESCRIPTION
**Pull request by WrobelKrakow**

### CODE REVIEW

File: core/src/main/java/pl/netigen/core/netigenapi/NetigenSplashFragment.kt [hunk 1]
```diff
@@ -132,6 +131,10 @@ abstract class NetigenSplashFragment<ViewModel : NetigenViewModel> : NetigenFrag
     }
 
     private fun initGDPRFragment() {
+        if (!canCommitFragments) {
+            consentNotShowed = true
+            return
+        }
         val fragment = netigenMainActivity.supportFragmentManager.findFragmentByTag(GDPR_POP_UP_TAG) as GDPRDialogFragment?
         if (fragment != null) {
             gdprDialogFragment = fragment
```
Comment (Micpol) [inline core/src/main/java/pl/netigen/core/netigenapi/NetigenSplashFragment.kt:140]: gdprDialogFragment should be treated as notNull here so that if there's an error we will be sure where it is. Though it's not quite possible to throw a NPE here

**Review by Micpol — CHANGES_REQUESTED** [review]

**Comment by Micpol** [comment]
Resolved

**Review by Micpol — APPROVED** [review]
